version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/ebctl
    binary: ebctl

archives:
  - formats: [ 'tar.gz' ]
    # this version template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      formats: [ 'zip' ]
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
blobs:
  - provider: s3
    region: us-east-1
    bucket: edgebit-releases
    directory: "releases/edgebit-cli/v{{.Version}}"

  - provider: s3
    region: us-east-1
    bucket: edgebit-releases
    directory: "releases/edgebit-cli/latest"

sboms:
  - artifacts: binary
