name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    permissions:
      id-token: write # For AWS OIDC
      contents: write # For publishing a release

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21.5"

      - name: Install Syft
        run: "curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin"

      - name: Run GoReleaser
        id: goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/releases/edgebit-cli/latest/*"

      - name: Find Linux SBOM
        run: echo LINUX_SBOM=$(jq -r '.[] | select(.name | contains("linux_amd64.sbom")) | .name' <<< '${{ steps.goreleaser.outputs.artifacts }}') >> $GITHUB_ENV

      - name: Upload SBOM to EdgeBit
        uses: edgebitio/edgebit-build@v1
        with:
          edgebit-url: "https://edgebit.edgebit.io"
          token: ${{ secrets.EDGEBIT_TOKEN }}
          sbom-file: "dist/${{ env.LINUX_SBOM }}"
          component: "edgebitio-edgebit-cli"
          tags: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
